name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      # RIGHT SIDE — Base Metrics Card
      - name: Base Metrics
        uses: lowlighter/metrics@latest

        with:
          filename: github-metrics.svg

          token: ${{ secrets.METRICS_TOKEN }}

          user: Gappyjosuke

          config_timezone: Asia/Kolkata

          base: header, activity

      # LEFT SIDE — Isometric Contribution Calendar
      - name: Isometric Calendar
        uses: lowlighter/metrics@latest

        with:
          filename: metrics.plugin.isocalendar.svg

          token: ${{ secrets.METRICS_TOKEN }}

          user: Gappyjosuke

          base: ""

          config_timezone: Asia/Kolkata

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
